# Generated by Django 5.2 on 2025-04-23 13:04
from django.core.management import call_command
from django.db import migrations


def load_initial_ranks(apps, schema_editor):
    Rank = apps.get_model('users', 'RankModel')
    if not Rank.objects.exists():
        call_command('loaddata', '/app/base_ranks/init_ranks.json')

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_initial_ranks),
    ]
