# Generated by Django 5.2 on 2025-04-23 13:04
import os

from django.core.files import File
from django.core.management import call_command
from django.db import migrations


def load_initial_ranks_and_images(apps, schema_editor):
    Rank = apps.get_model('users', 'RankModel')

    if not Rank.objects.exists():
        call_command('loaddata', '/app/storage/base_ranks/init_ranks.json')

    image_path = '/app/storage/ranks/'

    for rank in Rank.objects.all():
        filename = f"{rank.rank_name.lower()}.jpg"
        full_path = os.path.join(image_path, filename)

        if os.path.exists(full_path):
            with open(full_path, 'rb') as img_file:
                rank.image.save(filename, File(img_file), save=True)


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_initial_ranks_and_images),
    ]
